[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "greenlet"
description = 'Mock greenlet to allow install on 3.11'
requires-python = ">=3.7"
dynamic = ["version"]


[tool.hatch.version]
path = "greenlet.py"
